version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abhi
      MYSQL_DATABASE: thoughts_db
      MYSQL_USER: abhi
      MYSQL_PASSWORD: abhi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nodeapp

  node:
    build: .
    container_name: my-app
    ports:
      - "80:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: abhi
      MYSQL_PASSWORD: abhi
      MYSQL_DATABASE: thoughts_db
    depends_on:
      - mysql
    networks:
      - nodeapp

volumes:
  mysql_data:

networks:
  nodeapp:
    driver: bridge

