name: Integration Node Note App - CI

on: 

  push:
    branches: [ "main" ]

jobs:

  Install-and-build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4  

      - name: Defining Node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Building Application
        run: |
          npm run build
  
  Trivy-fs-scan:
    needs: Install-and-build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies (IMPORTANT)
        run: npm ci
      
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '1'


  Build-and-push-image:
    needs: Trivy-fs-scan
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Building Docker Images
        run: | 
          docker build --no-cache --file Dockerfile . -t ${{secrets.DOCKERHUB_USERNAME}}/note-app:latest
      
      # Cache Trivy DB (IMPORTANT)
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{secrets.DOCKERHUB_USERNAME}}/note-app:latest
          severity: "HIGH,CRITICAL"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"

      - name: Push Image to Docker hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/note-app:latest